all:
	antlr4 -Dlanguage=Python3 -visitor JavaLexer.g4 
	antlr4 -Dlanguage=Python3 -visitor JavaParser.g4 
	antlr4 -Dlanguage=Python3 -visitor JavadocLexer.g4 
	antlr4 -Dlanguage=Python3 -visitor JavadocParser.g4 
